-keep class io.github.theodorekonikowski.harbor.privileged.shizuku.HarborUserService { public <init>(); public <init>(android.content.Context); }
-keep class io.github.theodorekonikowski.harbor.privileged.shizuku.IHarborUserService$Stub { *; }
