-keep class com.monstera.harbor.privileged.shizuku.HarborUserService { public <init>(); public <init>(android.content.Context); }
-keep class com.monstera.harbor.privileged.shizuku.IHarborUserService$Stub { *; }
